### ISSUE TITLE
TribeEvents shortcode not working.

### ISSUE THREAD

**Issue by joeyaenv** [danrcoull/SuttonSilver_WordpressProductPage#1]
Hi , 

I have the latest version of the events calender installed and also the latest version of the pro version on the wp side of things. 

I am trying to use the TribalEvents shortcode but I get the following error:

Fatal error: Uncaught Error: Call to undefined function SuttonSilver\WordpressProductPage\Shortcode\tribe_is_event_query() ;

It also can't find the Tribe_Events_Pro__Shortcodes_Tribe_Events() class. 

Do you have any idea how to fix this ?

**Comment by danrcoull** [comment]
Not a publiic usable module. Sorry
